import { Component } from '@angular/core';

@Component({
  selector: 'test-page',
  templateUrl: './test-page.component.html',
  styleUrls: ['./test-page.component.scss']
})
export class TestPageComponent {
  maniFest = { "name": "069t000000N0bn1AAB", "type": "png", "aspectRatio": 6.5, "averageColor": "5b616e", "versions": [{ "format": "webp", "sizeKB": 9, "width": 800, "height": 123 }, { "format": "jpg", "sizeKB": 10, "width": 800, "height": 123 }, { "format": "png", "sizeKB": 8, "width": 800, "height": 123 }, { "format": "webp", "sizeKB": 22, "width": 700, "height": 108 }, { "format": "jpg", "sizeKB": 9, "width": 700, "height": 108 }, { "format": "png", "sizeKB": 17, "width": 700, "height": 108 }, { "format": "webp", "sizeKB": 18, "width": 600, "height": 92 }, { "format": "jpg", "sizeKB": 7, "width": 600, "height": 92 }, { "format": "png", "sizeKB": 14, "width": 600, "height": 92 }, { "format": "webp", "sizeKB": 14, "width": 500, "height": 77 }, { "format": "jpg", "sizeKB": 6, "width": 500, "height": 77 }, { "format": "png", "sizeKB": 11, "width": 500, "height": 77 }, { "format": "webp", "sizeKB": 11, "width": 400, "height": 62 }, { "format": "jpg", "sizeKB": 4, "width": 400, "height": 62 }, { "format": "png", "sizeKB": 9, "width": 400, "height": 62 }, { "format": "webp", "sizeKB": 10, "width": 350, "height": 54 }, { "format": "jpg", "sizeKB": 4, "width": 350, "height": 54 }, { "format": "png", "sizeKB": 8, "width": 350, "height": 54 }, { "format": "webp", "sizeKB": 8, "width": 300, "height": 46 }, { "format": "jpg", "sizeKB": 3, "width": 300, "height": 46 }, { "format": "png", "sizeKB": 7, "width": 300, "height": 46 }, { "format": "webp", "sizeKB": 6, "width": 250, "height": 38 }, { "format": "jpg", "sizeKB": 3, "width": 250, "height": 38 }, { "format": "png", "sizeKB": 5, "width": 250, "height": 38 }, { "format": "webp", "sizeKB": 4, "width": 200, "height": 31 }, { "format": "jpg", "sizeKB": 2, "width": 200, "height": 31 }, { "format": "png", "sizeKB": 4, "width": 200, "height": 31 }, { "format": "webp", "sizeKB": 4, "width": 150, "height": 23 }, { "format": "jpg", "sizeKB": 1, "width": 150, "height": 23 }, { "format": "png", "sizeKB": 3, "width": 150, "height": 23 }, { "format": "webp", "sizeKB": 2, "width": 100, "height": 15 }, { "format": "jpg", "sizeKB": 1, "width": 100, "height": 15 }, { "format": "png", "sizeKB": 3, "width": 100, "height": 15 }, { "format": "webp", "sizeKB": 1, "width": 50, "height": 8 }, { "format": "jpg", "sizeKB": 1, "width": 50, "height": 8 }, { "format": "png", "sizeKB": 2, "width": 50, "height": 8 }, { "format": "webp", "sizeKB": 1, "width": 25, "height": 4 }, { "format": "jpg", "sizeKB": 1, "width": 25, "height": 4 }, { "format": "png", "sizeKB": 1, "width": 25, "height": 4 }] }

}
