#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run check
# npm run git-format-staged -- -f 'prettier --ignore-unknown --stdin --stdin-filepath \"{}\"' '*.ts' '*.tsx' '*.json' '*.scss' '*.html'
